import Head from "next/head";
import { MutableRefObject, useRef, useState } from "react";
import Navbar from "../src/components/Navbar";
import Introduction from "../src/sections/Introduction";
import { GlobalContext } from "../src/context/useGlobalContext";
import Sidebar from "../src/components/Sidebar";
import About from "../src/sections/About";
import { navItemTitles } from "../src/data/navItems";
import Skills from "../src/sections/Skills";

export default function Home() {
  const [sidebar, setSidebar] = useState(false);
  const [visibleSection, setVisibleSection] = useState("");
  const aboutRef = useRef() as MutableRefObject<HTMLElement>;
  const skillsRef = useRef() as MutableRefObject<HTMLElement>;
  const sectionRefs = [
    { section: navItemTitles.About, ref: aboutRef },
    { section: navItemTitles.Skills, ref: skillsRef }
  ];
  return (
    <>
      <GlobalContext.Provider
        value={{
          isSidebarOpen: sidebar,
          setSidebar,
          visibleSection,
          setVisibleSection,
        }}
      >
        <Head>
          <title>Sreejit De</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="true"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap"
            rel="stylesheet"
          />
        </Head>
        <Navbar refs={sectionRefs} />
        <Sidebar refs={sectionRefs} />
        <Introduction />
        <About ref={aboutRef} />
        <Skills ref={skillsRef} />
      </GlobalContext.Provider>
    </>
  );
}
